### ISSUE TITLE
need more escaping

### ISSUE THREAD

**Issue by dwunsch** [unicredit/sbt-swagger-codegen#23]
there's actually two issues here:
a) parameter names and values are not URI-encoded in a query string
b) a parameter name might contain characters that are illegal in method parameter names, for example a parameter "a-b" would produce `a-b:String`which scalac will not compile

**Comment by andreaTP** [comment]
this still need some testing

**Comment by andreaTP** [comment]
I just published a SNAPSHOT to let you check everything:
https://oss.sonatype.org/content/repositories/snapshots/eu/unicredit/sbt-swagger-codegen_2.10_0.13/0.0.7-SNAPSHOT/

**Comment by dwunsch** [comment]
this is still broken, and requires changes in the code generation.
i don't know how to get treehugger to generate backticked method/parameter-names, though.
and even if i did - someone could put a backtick in the name itself...

**Comment by andreaTP** [comment]
treehugger should do it automagically if needed:
https://github.com/eed3si9n/treehugger/blob/master/library/src/main/scala/treehugger/TreePrinters.scala#L17

**Comment by dwunsch** [comment]
it does when i have an input parameter called "this" (which is a keyword) but not when it's called something like "correlation-id" (which is not  a keyword, but not a un-backticked name either)

**Comment by andreaTP** [comment]
uhm, which are the invariants on this?
just names that contains special characters like "-" or start with a number, what else?

**Comment by dwunsch** [comment]
i've seen "-" causing trouble, investigated a bit, found it too hard to fix immediately and decided i'd just open a somewhat generic issue and maybe deal with it later.

**Comment by fralken** [comment]
Scalameta backticks parameters names automatically when needee
